export const FETCH_PRODUCT = 'FETCH_PRODUCT'
export const ADD_TO_CART = 'ADD_TO_CART'
export const PLUS_ITEM = 'PLUS_ITEM'
export const MINUS_ITEM = 'MINUS_ITEM'
export const REMOVE_FROM_CART = 'REMOVE_FROM_CART'
export const LOGGED_IN = 'LOGGED_IN'
export const LOGGED_OUT = 'LOGGED_OUT'
export const SUBMIT_ORDER = 'SUBMIT_ORDER'